// AUTO-GENERATED by tools/gen_state_schema.py - do not edit manually.
// To regenerate: python tools/gen_state_schema.py
// Import in a JS module: /** @import {StateResponse} from './lib/state_schema.js' */

/**
 * @typedef {AramPayload|ArenaPayload|BrawlPayload|SrPayload|TftPayload} CoachPayload
 */

/**
 * @typedef {Object} AramPayload
 * @property {string} mode
 * @property {string} action
 * @property {Object} combat_stats
 * @property {Array} stat_shards
 * @property {string} champion
 * @property {string} immediate
 * @property {string} fight_rule
 * @property {string} positioning
 * @property {string} reset_item
 * @property {string} objective
 * @property {string} risk
 * @property {string} game_time
 * @property {number} game_time_s
 * @property {number} hp_pct
 * @property {string} kda
 * @property {Object} ally_spells
 * @property {string} items_display
 * @property {string} game_mode
 * @property {boolean} mayhem
 * @property {string} my_team
 * @property {string} item_build
 * @property {string} item_extra
 * @property {Object} item_build_reasons
 * @property {number} my_tower_hp
 * @property {number} enemy_tower_hp
 * @property {number} wave_pct
 * @property {Array} hp_packs
 * @property {string} augments
 * @property {number} level
 * @property {number} gold
 */

/**
 * @typedef {Object} ArenaPayload
 * @property {string} mode
 * @property {string} action
 * @property {Object} combat_stats
 * @property {Array} stat_shards
 * @property {string} champion
 * @property {string} fight_rule
 * @property {string} round_strategy
 * @property {string} augment_advice
 * @property {string} anvil_advice
 * @property {string} target_priority
 * @property {string} risk
 * @property {string} immediate
 * @property {Array} teams
 * @property {string} round
 * @property {string} rank
 * @property {number} alive_teams
 * @property {number} hp_pct
 * @property {number} wins
 * @property {number} losses
 * @property {number} game_time_s
 * @property {boolean} camp_phase
 * @property {string} item_build
 * @property {Object} ally_spells
 * @property {string} pregame
 * @property {number|null} win_pct
 * @property {string} kda
 * @property {number} level
 * @property {number} gold
 * @property {Array} daemon_slayer_picks
 */

/**
 * @typedef {Object} BrawlPayload
 * @property {string} mode
 * @property {string} action
 * @property {Object} combat_stats
 * @property {Array} stat_shards
 * @property {string} champion
 * @property {string} immediate
 * @property {string} fight_rule
 * @property {string} wave
 * @property {string} reset_item
 * @property {string} objective
 * @property {string} risk
 * @property {number} game_time_s
 * @property {number} hp_pct
 * @property {string} kda
 * @property {number} gold
 * @property {string} game_mode
 * @property {Object} ally_spells
 * @property {number} my_nexus_hp
 * @property {number} enemy_nexus_hp
 * @property {Array} log
 * @property {number|null} win_pct
 * @property {Array} daemon_slayer_picks
 */

/**
 * @typedef {Object} SrPayload
 * @property {string} mode
 * @property {string} action
 * @property {Object} combat_stats
 * @property {Array} stat_shards
 * @property {string} immediate
 * @property {string} next
 * @property {string} fight_rule
 * @property {string} wave
 * @property {string} objective
 * @property {string} reset_item
 * @property {string} risk
 * @property {string} map
 * @property {number|null} win_pct
 * @property {Array} log
 * @property {string} pregame
 * @property {string} champion
 * @property {number} game_time_s
 * @property {number} hp_pct
 * @property {string} kda
 * @property {number} gold
 * @property {number} level
 * @property {number} cs
 * @property {Object} ally_spells
 * @property {Array} ally_comp
 * @property {Array} enemy_comp
 * @property {TeamContext|null} team_context
 */

/**
 * @typedef {Object} TftPayload
 * @property {string} mode
 * @property {string} action
 * @property {Object} combat_stats
 * @property {Array} stat_shards
 * @property {string} board
 * @property {string} econ
 * @property {string} rolldown
 * @property {string} items
 * @property {string} god_pick
 * @property {string} placement
 * @property {string} upgrade
 * @property {string} risk
 * @property {number} game_time_s
 * @property {string} stage
 * @property {string} round
 * @property {number} level
 * @property {number} gold
 * @property {number} health
 */

/**
 * @typedef {Object} HealthBlock
 * @property {boolean|null} alive
 * @property {number|null} pid
 * @property {string|null} mode
 * @property {boolean|null} has_game
 * @property {number|null} ui_pulse_age_s
 * @property {number|null} game_poll_age_s
 */

/**
 * @typedef {Object} StateResponse
 * @property {string} mode_key
 * @property {string} coach_source
 * @property {HealthBlock} health
 * @property {CoachPayload} coach
 * @property {Object|null} liveclient
 * @property {Object|null} lcu
 */

/**
 * @typedef {Object} HealthAllResponse
 * @property {string} status
 * @property {Object} rc
 * @property {Object} vision
 * @property {Object} daemon_slayer
 * @property {Object} supervisor
 * @property {Object} cost
 * @property {Object} bridge
 * @property {Object} peers
 * @property {string} rc_version
 */

/**
 * @typedef {Object} HealthResponse
 * @property {boolean|null} alive
 * @property {number|null} pid
 * @property {string|null} mode
 * @property {string} rc_version
 */

/**
 * @typedef {Object} PeerHealth
 * @property {number|null} age_s
 * @property {boolean} stale
 * @property {boolean} watcher_alive
 * @property {string} status
 */

/**
 * @typedef {Object} DsPreviewItem
 * @property {string} item_id
 * @property {string} item_name
 * @property {number} delta_dps
 * @property {number} gold
 * @property {string} scorer
 */

/**
 * @typedef {Object} DsPreviewResponse
 * @property {boolean} ok
 * @property {Array} ranked
 * @property {string} scorer
 * @property {string} archetype
 * @property {string} error
 */

export {};
