"""RM-95 / A-26: ability-data coverage must distinguish ABSENT from CURRENT.

Two guards already exist in ``core/daemon_slayer_client``:

* :func:`champion_has_ability_data` - "is the champion PRESENT in the Meraki
  bulk map?" (RM-79).
* :func:`champion_ability_data_is_current` - "are the stored values still
  RIGHT?" (RM-81), read off ``<patch>/ability_staleness.json``.

They were never composed, and the staleness report is generated by iterating
``champion_abilities.json`` itself - so a champion ABSENT from that file can
never become a check target, never lands in ``stale_champions``, and therefore
came back "current". The staleness program certified as clean exactly the two
champions (16.14.1: Locke, Zaahen) that have no ability data at all.

:func:`champion_ability_data_status` is the composed tri-state. The fail-soft
contract is unchanged and load-bearing: a missing / unreadable REPORT must stay
quiet for the whole roster. That is a different failure from a champion having
no ability data, and conflating the two is what the original docstring calls
unacceptable. Both are pinned below.

Every case resets BOTH module caches (``_champ_ability_index``,
``_champ_stale_index``) plus ``_champ_attackrange_index``, because a leaked
cache makes these tests pass or fail on ordering rather than on behavior.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest

import core.daemon_slayer_client as M

_REAL_DS_DATA_DIR = M._DS_DATA_DIR


@pytest.fixture(autouse=True)
def _reset_caches():
    """Drop every champion-keyed cache before AND after each case."""
    def _clear():
        M._champ_ability_index = None
        M._champ_stale_index = None
        M._champ_attackrange_index = None

    _clear()
    yield
    M._DS_DATA_DIR = _REAL_DS_DATA_DIR
    _clear()


def _point_at(tmp_path: Path, *, abilities, staleness, patch: str = "16.14.1"):
    """Build a synthetic DS data dir. ``None`` means "write no file at all"."""
    (tmp_path / "current.txt").write_text(patch, encoding="utf-8")
    (tmp_path / patch).mkdir(parents=True, exist_ok=True)
    if abilities is not None:
        (tmp_path / patch / "champion_abilities.json").write_text(
            json.dumps(abilities), encoding="utf-8"
        )
    if staleness is not None:
        (tmp_path / patch / "ability_staleness.json").write_text(
            json.dumps(staleness), encoding="utf-8"
        )
    M._DS_DATA_DIR = tmp_path
    M._champ_ability_index = None
    M._champ_stale_index = None
    M._champ_attackrange_index = None


def _live_patch() -> str:
    return (_REAL_DS_DATA_DIR / "current.txt").read_text(encoding="utf-8").strip()


def _live_roster() -> dict:
    """{ddragon_id: display_name} straight off the shipped champions.json."""
    raw = (_REAL_DS_DATA_DIR / _live_patch() / "champions.json").read_text(
        encoding="utf-8"
    )
    data = json.loads(raw).get("data") or {}
    return {cid: str((rec or {}).get("name") or cid) for cid, rec in data.items()}


def _live_ability_keys() -> set:
    raw = (_REAL_DS_DATA_DIR / _live_patch() / "champion_abilities.json").read_text(
        encoding="utf-8"
    )
    doc = json.loads(raw)
    doc = doc.get("data") if isinstance(doc.get("data"), dict) else doc
    return {M._norm_champ_key(str(k)) for k in (doc or {})}


# ---------------------------------------------------------------------------
# 1. The alias half - keyed off the shipped data file, never a literal list.
# ---------------------------------------------------------------------------


def test_every_display_name_resolves_like_its_ddragon_id():
    """Data-driven over the WHOLE shipped roster.

    ``champion_abilities.json`` is id-keyed while the Live Client and the
    build-order keyspace are display-name keyed. Plain lowercase-and-strip
    normalization bridges only the punctuation variants; the names carrying an
    extra or different word ("Wukong" -> MonkeyKing, "Nunu & Willump" -> Nunu,
    "Renata Glasc" -> Renata) need the canonical DDragon resolver.

    Deriving the pairs from champions.json rather than hardcoding them means a
    future rename or release cannot silently make this vacuous.
    """
    roster = _live_roster()
    assert len(roster) >= 150, "roster read looks wrong - refusing a vacuous pass"

    divergent = {cid: name for cid, name in roster.items() if name != cid}
    assert divergent, "expected at least some display names to differ from ids"

    mismatched = []
    for cid, name in roster.items():
        if (
            M.champion_has_ability_data(name) != M.champion_has_ability_data(cid)
            or M.champion_ability_data_status(name)
            != M.champion_ability_data_status(cid)
            or M.champion_attackrange(name) != M.champion_attackrange(cid)
        ):
            mismatched.append((name, cid))
    assert not mismatched, f"display name must resolve like its id: {mismatched}"


def test_non_normalizable_names_are_actually_exercised():
    """Guards the test above: the hard cases must still be IN the roster.

    If a rename ever made every display name a plain punctuation variant of its
    id, the parity sweep would pass without proving anything about the
    canonical resolver. This fails loudly instead.
    """
    roster = _live_roster()
    hard = [
        (name, cid)
        for cid, name in roster.items()
        if M._norm_champ_key(name) != M._norm_champ_key(cid)
    ]
    assert hard, (
        "no display name needs the canonical resolver any more - the parity "
        "sweep above has gone vacuous and this suite needs revisiting"
    )
    for name, cid in hard:
        assert M._canon_champ_key(name) == M._canon_champ_key(cid), (
            f"{name!r} must canonicalize onto {cid!r}"
        )


# ---------------------------------------------------------------------------
# 2. The certification half - absent data must report ABSENT, not current.
# ---------------------------------------------------------------------------


def test_live_absent_champions_report_absent():
    """Derived from the shipped data, not from a champion literal.

    The absent set is (champions.json roster) minus (champion_abilities.json
    keyspace) - Meraki's bulk map carries 171 of 173 at 16.14.1.
    """
    roster = _live_roster()
    ability_keys = _live_ability_keys()
    absent = sorted(
        cid for cid in roster if M._norm_champ_key(cid) not in ability_keys
    )
    assert absent, "no absent champions on disk - nothing for this case to prove"

    for cid in absent:
        assert M.champion_has_ability_data(cid) is False
        assert M.champion_ability_data_status(cid) == M.ABILITY_DATA_ABSENT, (
            f"{cid!r} has no ability data at all and must not be certified"
        )
        assert M.champion_ability_data_is_current(cid) is False, (
            f"{cid!r} was certified 'current' with zero stored ability values"
        )
        # Also via display name - the alias path must not launder it back.
        assert (
            M.champion_ability_data_status(roster[cid]) == M.ABILITY_DATA_ABSENT
        )

    present = [cid for cid in roster if cid not in set(absent)]
    assert present
    for cid in present[:25]:
        assert M.champion_ability_data_status(cid) != M.ABILITY_DATA_ABSENT


def test_locke_and_zaahen_are_the_absent_set_at_1614():
    """Pins the RM-95 finding against the shipped 16.14.1 snapshot."""
    if _live_patch() != "16.14.1":
        pytest.skip("pinned to the 16.14.1 snapshot")
    roster = _live_roster()
    ability_keys = _live_ability_keys()
    absent = sorted(
        cid for cid in roster if M._norm_champ_key(cid) not in ability_keys
    )
    assert absent == ["Locke", "Zaahen"]
    for cid in absent:
        assert M.champion_ability_data_status(cid) == M.ABILITY_DATA_ABSENT
        assert M.champion_ability_data_is_current(cid) is False


def test_absent_beats_stale_on_a_synthetic_snapshot(tmp_path):
    """Never rots with the roster: pure synthetic fixture.

    A champion with no ability entry reports ABSENT even when it is also named
    in the staleness report - ABSENT is the stronger, more actionable signal
    (no data to refresh, blocked upstream) and must not be masked as STALE.
    """
    _point_at(
        tmp_path,
        abilities={"data": {"Garen": {}, "Lux": {}}},
        staleness={"stale_champions": ["Lux", "Ghost"]},
    )
    assert M.champion_ability_data_status("Ghost") == M.ABILITY_DATA_ABSENT
    assert M.champion_ability_data_status("Lux") == M.ABILITY_DATA_STALE
    assert M.champion_ability_data_status("Garen") == M.ABILITY_DATA_CURRENT

    assert M.champion_ability_data_is_current("Ghost") is False
    assert M.champion_ability_data_is_current("Lux") is False
    assert M.champion_ability_data_is_current("Garen") is True


# ---------------------------------------------------------------------------
# 3. The fail-soft contract - report problems must stay quiet for EVERYONE.
# ---------------------------------------------------------------------------


def test_missing_ability_map_stays_quiet_for_the_whole_roster(tmp_path):
    """No champion_abilities.json is a SNAPSHOT problem, not per-champion absence.

    This is the distinction the original docstring insists on: "no report" and
    "this champion has no data" are different failures. Nobody may be flagged
    ABSENT off a missing map.
    """
    _point_at(tmp_path, abilities=None, staleness={"stale_champions": []})
    for champ in ("Garen", "Locke", "Zaahen", "Nunu & Willump", "NotAChampion"):
        assert M.champion_has_ability_data(champ) is True
        assert M.champion_ability_data_status(champ) == M.ABILITY_DATA_CURRENT
        assert M.champion_ability_data_is_current(champ) is True


def test_unreadable_ability_map_stays_quiet(tmp_path):
    _point_at(tmp_path, abilities={"data": {"Garen": {}}}, staleness=None)
    (tmp_path / "16.14.1" / "champion_abilities.json").write_text(
        "{not json", encoding="utf-8"
    )
    M._champ_ability_index = None
    for champ in ("Garen", "Locke", "Zaahen"):
        assert M.champion_ability_data_status(champ) == M.ABILITY_DATA_CURRENT
        assert M.champion_ability_data_is_current(champ) is True


def test_missing_staleness_report_stays_quiet(tmp_path):
    """Absence of evidence is not evidence of staleness (unchanged RM-81 rule)."""
    _point_at(tmp_path, abilities={"data": {"Garen": {}, "Lux": {}}}, staleness=None)
    assert M.champion_ability_data_status("Garen") == M.ABILITY_DATA_CURRENT
    assert M.champion_ability_data_status("Lux") == M.ABILITY_DATA_CURRENT
    assert M.champion_ability_data_is_current("Lux") is True
    # ...but a champion genuinely missing from the PRESENT map is still ABSENT.
    assert M.champion_ability_data_status("Ghost") == M.ABILITY_DATA_ABSENT


def test_unreadable_staleness_report_stays_quiet(tmp_path):
    _point_at(
        tmp_path,
        abilities={"data": {"Garen": {}, "Lux": {}}},
        staleness={"stale_champions": ["Lux"]},
    )
    (tmp_path / "16.14.1" / "ability_staleness.json").write_text(
        "{not json", encoding="utf-8"
    )
    M._champ_stale_index = None
    assert M.champion_ability_data_status("Lux") == M.ABILITY_DATA_CURRENT
    assert M.champion_ability_data_is_current("Lux") is True


def test_both_reports_missing_stays_quiet(tmp_path):
    _point_at(tmp_path, abilities=None, staleness=None)
    for champ in ("Garen", "Locke", "Zaahen"):
        assert M.champion_ability_data_status(champ) == M.ABILITY_DATA_CURRENT
        assert M.champion_ability_data_is_current(champ) is True


def test_status_values_are_the_three_declared_constants(tmp_path):
    _point_at(
        tmp_path,
        abilities={"data": {"Garen": {}, "Lux": {}}},
        staleness={"stale_champions": ["Lux"]},
    )
    allowed = {
        M.ABILITY_DATA_ABSENT,
        M.ABILITY_DATA_STALE,
        M.ABILITY_DATA_CURRENT,
    }
    assert len(allowed) == 3
    for champ in ("Garen", "Lux", "Ghost", "", "   ", "Zzzzz'Qqqq"):
        assert M.champion_ability_data_status(champ) in allowed
        assert isinstance(M.champion_ability_data_is_current(champ), bool)
