"""A-21 / RM-90 S1 tail - the FLAT keyspace generator must be able to pass score_by.

The A-21 build slice plumbed ``score_by`` through ``core/build_order.py`` and
``core/build_order_precompute.py``, which covers the comp-archetype keyspace
(``data/daemon_slayer/build_orders/<patch>/``). The FLAT damage-profile keyspace
(``data/daemon_slayer/<patch>/build_orders_sr.json``) is generated by
``tools/daemon_slayer_build_orders_generate.py``, which called ``plan_build_order``
with no ``score_by`` and exposed no CLI flag - so that keyspace could never emit
the seam. Both keyspaces need it (reference_build_order_two_keyspaces_both_need_regen).

Confirmed API surface before scaffolding:
  * ``plan_build_order(..., score_by: str = SCORE_BY_DEFAULT)`` - core/build_order.py:516.
  * ``SCORE_BY_DEFAULT = "blended"`` / ``SCORE_BY_VALUES`` - core/build_order.py:253-254.
  * generator call site - tools/daemon_slayer_build_orders_generate.py:191-207.
  * generator argparse - tools/daemon_slayer_build_orders_generate.py:291-301.

DEFAULT-OFF: the default must not insert ``score_by`` into the call at all, so a
run that does not ask for the seam is byte-identical to today's generator.
"""
from __future__ import annotations

import importlib
import unittest

_GEN = importlib.import_module("tools.daemon_slayer_build_orders_generate")


class _Recorder:
    """Stand-in for plan_build_order that records the kwargs it was handed."""

    def __init__(self):
        self.calls: list[dict] = []

    def __call__(self, *args, **kwargs):
        self.calls.append(kwargs)
        return None  # -> build_order_for_class returns [], which is fine here


class GeneratorScoreByTests(unittest.TestCase):
    def setUp(self):
        self._orig = _GEN.plan_build_order
        self.rec = _Recorder()
        _GEN.plan_build_order = self.rec

    def tearDown(self):
        _GEN.plan_build_order = self._orig

    def test_default_does_not_pass_score_by(self):
        _GEN.build_order_for_class("Leona", "tank", "sr", "balanced")
        self.assertEqual(len(self.rec.calls), 1)
        self.assertNotIn("score_by", self.rec.calls[0])

    def test_explicit_default_also_omits_it(self):
        """Passing the default explicitly stays byte-identical to omitting it."""
        _GEN.build_order_for_class(
            "Leona", "tank", "sr", "balanced", score_by=_GEN.SCORE_BY_DEFAULT,
        )
        self.assertNotIn("score_by", self.rec.calls[0])

    def test_non_default_reaches_plan_build_order(self):
        _GEN.build_order_for_class(
            "Leona", "tank", "sr", "balanced", score_by="team_blended",
        )
        self.assertEqual(self.rec.calls[0].get("score_by"), "team_blended")

    def test_threads_through_champion_and_mode_layers(self):
        _GEN.build_orders_for_champion("Leona", "sr", score_by="team_blended")
        self.assertTrue(self.rec.calls)
        for call in self.rec.calls:
            self.assertEqual(call.get("score_by"), "team_blended")

    def test_generate_mode_threads_it(self):
        _GEN.generate_mode("sr", ["Leona"], "16.14.1", score_by="team_blended")
        self.assertTrue(self.rec.calls)
        for call in self.rec.calls:
            self.assertEqual(call.get("score_by"), "team_blended")

    def test_generate_mode_default_omits_it(self):
        _GEN.generate_mode("sr", ["Leona"], "16.14.1")
        self.assertTrue(self.rec.calls)
        for call in self.rec.calls:
            self.assertNotIn("score_by", call)


class GeneratorCliTests(unittest.TestCase):
    def test_cli_exposes_score_by_with_the_shared_whitelist(self):
        parser = _GEN._build_arg_parser()
        args = parser.parse_args(["--mode", "sr", "--score-by", "team_blended"])
        self.assertEqual(args.score_by, "team_blended")

    def test_cli_defaults_to_blended(self):
        parser = _GEN._build_arg_parser()
        args = parser.parse_args([])
        self.assertEqual(args.score_by, _GEN.SCORE_BY_DEFAULT)

    def test_cli_rejects_an_unknown_value(self):
        parser = _GEN._build_arg_parser()
        with self.assertRaises(SystemExit):
            parser.parse_args(["--score-by", "not_a_metric"])


if __name__ == "__main__":
    unittest.main()
