"""Auto-derives module map in docs/ARCHITECTURE.md from # arch: headers in .py files.

Each .py file may carry this comment in its first 8 lines:
    # arch: <role description> | section=<section> | frozen=<yes|no>

Sections (determines which table the file appears in):
    orchestration, vision, coaching, dashboard, core, bridge, tools, tft, agents, gamepc, test

Running without flags rewrites ARCHITECTURE.md (archmap:start/end) in-place.
Running with --check exits 1 if the file would change (use in pre-commit).

Note: the frozen-file list in CLAUDE.md is manually maintained because it
includes non-Python files (.ps1, .json, .xml, .md) that cannot carry # arch: headers.
"""
import argparse
import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).parent.parent

SKIP_DIRS = {
    "__pycache__", ".git", ".claude", "node_modules",
    "_archive", "docs",
}

SECTION_ORDER = [
    "orchestration",
    "vision",
    "coaching",
    "dashboard",
    "core",
    "bridge",
    "tools",
    "tft",
    "agents",
    "gamepc",
    "test",
]

SECTION_TITLES = {
    "orchestration": "Orchestration (all frozen — do not edit without sign-off)",
    "vision": "Vision + data pipeline",
    "coaching": "Coaching",
    "dashboard": "Dashboard",
    "core": "Core utilities",
    "bridge": "Bridge tools",
    "tools": "Tools / ops",
    "tft": "TFT engine",
    "agents": "Phase 3 agents",
    "gamepc": "Game-PC agents",
    "test": "Tests",
}

ARCH_RE = re.compile(
    r"#\s*arch:\s*(?P<role>[^|]+?)\s*\|\s*section=(?P<section>\w+)\s*\|\s*frozen=(?P<frozen>yes|no)",
    re.IGNORECASE,
)


def _collect() -> dict[str, list[tuple[str, str, bool]]]:
    """Returns {section: [(rel_path, role, frozen), ...]} sorted by path."""
    data: dict[str, list] = {s: [] for s in SECTION_ORDER}

    for py in sorted(ROOT.rglob("*.py")):
        parts = set(py.relative_to(ROOT).parts)
        if parts & SKIP_DIRS:
            continue
        try:
            head = py.read_text(encoding="utf-8", errors="replace").splitlines()[:8]
        except OSError:
            continue
        for line in head:
            m = ARCH_RE.search(line)
            if m:
                section = m.group("section").lower()
                role = m.group("role").strip()
                frozen = m.group("frozen").lower() == "yes"
                rel = py.relative_to(ROOT).as_posix()
                if section in data:
                    data[section].append((rel, role, frozen))
                break

    return data


def _render_archmap(data: dict) -> str:
    lines = ["<!-- archmap:start — auto-generated by tools/gen_archmap.py; do not edit manually -->"]
    for section in SECTION_ORDER:
        entries = data.get(section, [])
        if not entries:
            continue
        title = SECTION_TITLES.get(section, section.title())
        lines.append(f"\n### {title}")
        lines.append("| File | Role |")
        lines.append("|---|---|")
        for rel, role, frozen in entries:
            frozen_tag = " [FROZEN]" if frozen else ""
            lines.append(f"| `{rel}` | {role}{frozen_tag} |")
    lines.append("\n<!-- archmap:end -->")
    return "\n".join(lines)


def _replace_between(text: str, start_marker: str, end_marker: str, replacement: str) -> str:
    start_re = re.compile(re.escape(start_marker) + r".*?$", re.MULTILINE)
    end_re = re.compile(r"^.*?" + re.escape(end_marker), re.MULTILINE)
    m_start = start_re.search(text)
    m_end = end_re.search(text, m_start.end() if m_start else 0)
    if not m_start or not m_end:
        return text  # sentinels missing — leave file unchanged
    return text[: m_start.start()] + replacement + text[m_end.end() :]


def _update_file(path: pathlib.Path, start_marker: str, end_marker: str, new_block: str, check: bool) -> bool:
    """Returns True if the file was (or would be) changed."""
    original = path.read_text(encoding="utf-8")
    updated = _replace_between(original, start_marker, end_marker, new_block)
    if updated == original:
        return False
    if not check:
        tmp = path.with_suffix(path.suffix + ".tmp")
        tmp.write_text(updated, encoding="utf-8")
        tmp.replace(path)
    return True


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Exit 1 if ARCHITECTURE.md would change")
    args = parser.parse_args()

    data = _collect()
    arch_md = ROOT / "docs" / "ARCHITECTURE.md"
    archmap_block = _render_archmap(data)

    changed = _update_file(
        arch_md,
        "<!-- archmap:start",
        "<!-- archmap:end -->",
        archmap_block,
        args.check,
    )

    if changed:
        if args.check:
            print(f"archmap out of sync — run `python tools/gen_archmap.py` to update: docs/ARCHITECTURE.md", file=sys.stderr)
            return 1
        print("Updated: docs/ARCHITECTURE.md")
    else:
        print("archmap up to date.")

    return 0


if __name__ == "__main__":
    sys.exit(main())
