# arch: generates web/js/lib/state_schema.js JSDoc typedefs from pydantic models | section=tools | frozen=no
"""Generate JSDoc @typedef blocks from RC pydantic schema models.

Sources introspected:
    dashboard/api_schema.py  - HTTP envelope shapes (StateResponse, HealthBlock, ...)
    core/coaching_payload.py - per-mode coaching payload fields

Output:
    web/js/lib/state_schema.js

The generated file gives VS Code's JS language server enough type information
to flag field-name typos (e.g. state.coach.enemy_comp vs enemy_team) without
requiring TypeScript compilation.

Run:
    python tools/gen_state_schema.py           # rewrite in-place
    python tools/gen_state_schema.py --check   # exit 1 if out of sync
"""
from __future__ import annotations

import argparse
import sys
import types as builtin_types
import typing
from pathlib import Path

ROOT = Path(__file__).parent.parent
sys.path.insert(0, str(ROOT))

from pydantic import BaseModel  # noqa: E402 - after sys.path insert

from dashboard.api_schema import (  # noqa: E402
    DsPreviewItem,
    DsPreviewResponse,
    HealthAllResponse,
    HealthBlock,
    HealthResponse,
    PeerHealth,
    StateResponse,
)
from core.coaching_payload import (  # noqa: E402
    AramPayload,
    ArenaPayload,
    BrawlPayload,
    SrPayload,
    TftPayload,
)

OUTPUT = ROOT / "web" / "js" / "lib" / "state_schema.js"

# Manual field-type overrides: model name -> {field name -> JSDoc type string}.
# Use when the Python annotation is looser than what JS callers actually need.
_OVERRIDES: dict[str, dict[str, str]] = {
    "StateResponse": {
        "coach": "CoachPayload",
    },
}

# Models to emit, in document order.
# Coaching payloads first - they contain the field names most likely to be mistyped.
_MODELS: list[type[BaseModel]] = [
    AramPayload,
    ArenaPayload,
    BrawlPayload,
    SrPayload,
    TftPayload,
    HealthBlock,
    StateResponse,
    HealthAllResponse,
    HealthResponse,
    PeerHealth,
    DsPreviewItem,
    DsPreviewResponse,
]


def _js_type(annotation: object) -> str:
    """Convert a Python type annotation to a JSDoc type string."""
    if annotation is None or annotation is type(None):
        return "null"
    if annotation is typing.Any:
        return "*"

    # Python 3.10+ union syntax: X | Y | None
    if isinstance(annotation, builtin_types.UnionType):
        args = typing.get_args(annotation)
        non_none = [a for a in args if a is not type(None)]
        nullable = type(None) in args
        base = "|".join(_js_type(a) for a in non_none)
        return f"{base}|null" if nullable and len(non_none) == 1 else base

    origin = typing.get_origin(annotation)
    args = typing.get_args(annotation)

    # Old-style Optional[X] = Union[X, None]
    if origin is typing.Union:
        non_none = [a for a in args if a is not type(None)]
        nullable = type(None) in args
        base = "|".join(_js_type(a) for a in non_none)
        return f"{base}|null" if nullable and len(non_none) == 1 else base

    if origin is list:
        return "Array"
    if origin is dict:
        return "Object"

    if annotation is str:
        return "string"
    if annotation is int or annotation is float:
        return "number"
    if annotation is bool:
        return "boolean"

    if isinstance(annotation, type) and issubclass(annotation, BaseModel):
        return annotation.__name__

    return "*"


def _model_typedef(model_cls: type[BaseModel]) -> str:
    """Generate a JSDoc @typedef block for one pydantic model."""
    name = model_cls.__name__
    overrides = _OVERRIDES.get(name, {})
    lines = ["/**", f" * @typedef {{Object}} {name}"]
    for field_name, field_info in model_cls.model_fields.items():
        if field_name in overrides:
            js_type = overrides[field_name]
        else:
            js_type = _js_type(field_info.annotation)
        lines.append(f" * @property {{{js_type}}} {field_name}")
    lines.append(" */")
    return "\n".join(lines)


def _generate() -> str:
    sections: list[str] = [
        "// AUTO-GENERATED by tools/gen_state_schema.py - do not edit manually.",
        "// To regenerate: python tools/gen_state_schema.py",
        "// Import in a JS module: /** @import {StateResponse} from './lib/state_schema.js' */",
        "",
        "/**",
        " * @typedef {AramPayload|ArenaPayload|BrawlPayload|SrPayload|TftPayload} CoachPayload",
        " */",
        "",
    ]
    for model_cls in _MODELS:
        sections.append(_model_typedef(model_cls))
        sections.append("")
    sections.append("export {};")
    sections.append("")
    return "\n".join(sections)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Exit 1 if state_schema.js is out of sync with pydantic models.",
    )
    args = parser.parse_args()

    content = _generate()

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing == content:
            return 0
        print("state_schema.js is out of sync - run: python tools/gen_state_schema.py")
        return 1

    OUTPUT.write_text(content, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
