# arch: secret-gist mirror of the Share/ review package | section=tools | frozen=no
"""Mirror C:\\Riot Commander\\Share into the secret review gist.

The gist is the low-friction external handoff. It holds exactly four files:
  * Share.zip                              the full review package (deterministic)
  * daemon_slayer_wiki_stats_extract.py    inline, readable
  * daemon_slayer_wiki_ability_extract.py  inline, readable
  * README.md                              a generated tldr

This script regenerates all four into the gist clone, commits, and pushes - so
the gist stays current every time Share/ changes. It is wired to a git
post-commit hook on the RC repo (fires only when a commit touches Share/).

Share/ itself is a deterministic mirror regenerated by tools/ds_share_sync.py;
this is the next link in that chain: Share/ -> secret gist.

CLONE_DIR is a local clone of the gist - a SEPARATE git repo, kept OUT of the RC
tree. Its git remote holds the gist id; nothing here hardcodes it. Override the
clone path with RC_SHARE_GIST_DIR.

The zip is byte-deterministic (fixed entry timestamps + sorted order) so an
unchanged Share/ produces an unchanged zip -> no spurious gist commit.
"""
from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import zipfile
from datetime import datetime, timezone
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARE_DIR = REPO_ROOT / "Share"
CLONE_DIR = Path(
    os.environ.get("RC_SHARE_GIST_DIR", r"C:\Users\Administrator\.rc-share-gist")
)
# Push-failure visibility (incident 2026-06-03 -> 2026-06-09: a swallowed
# non-fast-forward rejection left the published gist 45 commits / 6 days stale).
LOG_DIR = REPO_ROOT / "logs"
STATUS_PATH = REPO_ROOT / "ops" / "runtime" / "gist_sync_status.json"
PUSH_FAIL_EXIT = 3
# Bounded ceiling for every git subprocess. This runs from a post-commit hook;
# a network call (fetch / push) that hangs on a dead remote or a credential
# prompt would otherwise block the commit indefinitely. Local calls (add /
# status / commit) return well under this; the ceiling only ever trips on a
# stuck network op. Override with RC_SHARE_GIST_GIT_TIMEOUT_S.
GIT_TIMEOUT_S = float(os.environ.get("RC_SHARE_GIST_GIT_TIMEOUT_S", "120"))
WIKI_SCRIPTS = (
    "daemon_slayer_wiki_stats_extract.py",
    "daemon_slayer_wiki_ability_extract.py",
)
_EXCLUDE_DIR_NAMES = {"__pycache__"}
_EXCLUDE_SUFFIXES = (".pyc", ".pyo")
_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)  # fixed -> deterministic zip bytes

_README_TEMPLATE = """# Daemon Slayer - external review handoff

Daemon Slayer is an offline, deterministic League of Legends build-math
engine, packaged for external technical review. It scores item builds for a
champion against a target's defensive profile and ranks every purchasable
item per champion through role-specific archetype scorers. Pure Python
standard library: no third-party dependencies, no network at request time,
no keys, and every number reproducible by hand.

## Files in this gist

- **Share.zip** - the full self-contained review package: the engine source
  and tests, the versioned data snapshot for the patch stamped in the footer
  below, and five authored review docs. Unzip it and start at its
  `README.md`.
- **daemon_slayer_wiki_stats_extract.py** - standalone wiki data-alignment
  tool (per-champion scalar sidecar), included for provenance.
- **daemon_slayer_wiki_ability_extract.py** - standalone wiki data-alignment
  tool (per-ability param sidecar), included for provenance.
- This README.

## Quick start

Download and unzip `Share.zip`, open its `README.md`, and run the test suite
per its Start here section. Expected test outcome and known limitations are
documented in the package README.

## A note on the inline code comments

The scripts and the source inside Share.zip carry internal development tags -
version anchors and incremental change markers. They are historical
development notes, not part of any public contract or external dependency.

Review-only: all rights reserved - see `LICENSE.md` inside the package.

---
ENGINE_VERSION __EV__ - data patch __PATCH__
"""


def read_manifest() -> tuple[str, str]:
    """(engine_version, patch) parsed from Share/MANIFEST.md; '?' if absent."""
    ev = patch = "?"
    mf = SHARE_DIR / "MANIFEST.md"
    if mf.exists():
        text = mf.read_text(encoding="utf-8")
        m = re.search(r"ENGINE_VERSION:\s*([0-9][0-9.]*)", text)
        if m:
            ev = m.group(1)
        m = re.search(r"data patch:\s*([0-9][0-9.]*)", text)
        if m:
            patch = m.group(1)
    return ev, patch


def render_readme(ev: str, patch: str) -> str:
    return _README_TEMPLATE.replace("__EV__", ev).replace("__PATCH__", patch)


def iter_share_files():
    """Yield (abs_path, arcname) for every Share/ file minus build artifacts."""
    for path in sorted(SHARE_DIR.rglob("*"), key=lambda p: p.as_posix()):
        if not path.is_file():
            continue
        rel = path.relative_to(SHARE_DIR)
        if any(part in _EXCLUDE_DIR_NAMES for part in rel.parts):
            continue
        if path.suffix in _EXCLUDE_SUFFIXES:
            continue
        yield path, "Share/" + rel.as_posix()


def build_zip(dest: Path) -> int:
    """Write a byte-deterministic Share.zip at dest. Returns the entry count."""
    count = 0
    tmp = dest.with_name(dest.name + ".tmp")
    with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path, arcname in iter_share_files():
            info = zipfile.ZipInfo(arcname, date_time=_ZIP_EPOCH)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
            count += 1
    os.replace(tmp, dest)
    return count


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(CLONE_DIR), *args],
        check=True,
        capture_output=True,
        text=True,
        timeout=GIT_TIMEOUT_S,
    )


def _append_log(line: str) -> None:
    """Best-effort append of one line to logs/YYYY-MM-DD.log. Never raises."""
    try:
        LOG_DIR.mkdir(parents=True, exist_ok=True)
        stamp = datetime.now().strftime("%Y-%m-%d")
        ts = datetime.now().strftime("%H:%M:%S")
        with (LOG_DIR / f"{stamp}.log").open("a", encoding="utf-8") as fh:
            fh.write(f"{ts} gist_share_sync {line.rstrip(chr(10))}\n")
    except OSError:
        pass


def _write_status(ok: bool, detail: str, unpushed: int) -> None:
    """Atomically record the last push outcome for dashboard / rc_facts to read."""
    payload = {
        "ok": ok,
        "detail": detail,
        "unpushed_commits": unpushed,
        "ts": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
    }
    try:
        STATUS_PATH.parent.mkdir(parents=True, exist_ok=True)
        tmp = STATUS_PATH.with_name(STATUS_PATH.name + ".tmp")
        tmp.write_text(json.dumps(payload, indent=2), encoding="utf-8")
        tmp.replace(STATUS_PATH)
    except OSError:
        pass


def _unpushed_count() -> int:
    """Local commits not yet on origin/main. Best-effort; 0 on any git error."""
    try:
        _git("fetch", "origin")
        out = _git("rev-list", "--count", "origin/main..HEAD").stdout.strip()
        return int(out)
    except (subprocess.SubprocessError, ValueError):
        # SubprocessError covers CalledProcessError AND a fetch that hits
        # GIT_TIMEOUT_S (TimeoutExpired); either way this stays best-effort.
        return 0


def _do_push(ev: str, patch: str, n: int, url: str) -> int:
    """Push HEAD to the gist. On failure: log + record status + echo to stderr
    and return PUSH_FAIL_EXIT (so the caller / hook exits non-zero instead of
    silently swallowing). Returns 0 on success."""
    try:
        _git("push", "--force", "origin", "main")
    except subprocess.SubprocessError as exc:
        # CalledProcessError (rejected push) AND TimeoutExpired (a push that
        # hangs past GIT_TIMEOUT_S on a dead remote / credential prompt) both
        # land here, so the push-failure visibility path always runs instead of
        # the exception escaping uncaught. .stderr may be bytes/None on a
        # timeout - normalize defensively.
        raw = getattr(exc, "stderr", None)
        if isinstance(raw, bytes):
            raw = raw.decode("utf-8", "replace")
        stderr = (raw or "").strip() or str(exc)
        unpushed = _unpushed_count()
        line = (
            f"push FAILED (ENGINE {ev}, patch {patch}): {unpushed} local "
            f"commit(s) unpushed - {url} :: {stderr}"
        )
        _append_log(line)
        _write_status(False, stderr, unpushed)
        sys.stderr.write(f"gist_share_sync: {line}\n")
        return PUSH_FAIL_EXIT
    _write_status(True, "pushed", 0)
    _gc_clone()
    return 0


def _gc_clone() -> None:
    """Prune the now-unreferenced old history so the LOCAL clone stays small
    after each squash (else every prior Share.zip snapshot lingers as a loose
    object and the local .git re-grows toward the 582MB that broke the remote)."""
    try:
        _git("reflog", "expire", "--expire=now", "--all")
        _git("gc", "--prune=now", "--quiet")
    except subprocess.SubprocessError:
        pass


def _squash_to_root(msg: str) -> None:
    """Collapse the gist branch to ONE parentless commit of the current tree,
    dropping all prior history.

    The gist is a current-state MIRROR - its history carries no value, and one
    ~4MB Share.zip appended per sync bloated it past GitHub's gist size quota
    (incident 2026-06-21: 582MB .git / 179 commits -> 'Repository is above its
    size quota ... pre-receive hook declined', 37 commits stranded). Rolling a
    single commit each push keeps the published gist permanently small."""
    tree = _git("rev-parse", "HEAD^{tree}").stdout.strip()
    root = _git("commit-tree", tree, "-m", msg).stdout.strip()
    _git("reset", "--hard", root)


def _clear_clone() -> None:
    """Remove every tracked top-level entry except .git (gists are flat)."""
    for child in CLONE_DIR.iterdir():
        if child.name == ".git":
            continue
        if child.is_file():
            child.unlink()


def sync() -> int:
    if not (CLONE_DIR / ".git").is_dir():
        sys.stderr.write(
            f"gist clone missing at {CLONE_DIR}\n"
            "create the gist + clone it there first (see tools/gist_share_sync.py header)\n"
        )
        return 2

    ev, patch = read_manifest()
    _clear_clone()
    (CLONE_DIR / "README.md").write_text(render_readme(ev, patch), encoding="utf-8")
    for name in WIKI_SCRIPTS:
        src = SHARE_DIR / "src" / "tools" / name
        (CLONE_DIR / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    n = build_zip(CLONE_DIR / "Share.zip")

    _git("add", "-A")
    status = _git("status", "--porcelain").stdout.strip()
    url = _git("remote", "get-url", "origin").stdout.strip()
    # A prior failed push can leave a backlog even when Share/ is unchanged -
    # treat that as work to do (republish), not a false all-clear.
    unpushed = _unpushed_count()
    if not status and unpushed == 0:
        _write_status(True, "up to date", 0)
        print(f"gist up to date (no change) - {url}")
        return 0

    msg = (
        f"sync Share -> gist (ENGINE {ev}, patch {patch}, {n} files)\n\n"
        "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"
    )
    if status:
        _git("commit", "-m", msg)
    # Roll the entire gist into a single rolling commit BEFORE pushing so its
    # history can never re-accumulate past the size quota, then force-push it.
    _squash_to_root(msg)
    rc = _do_push(ev, patch, n, url)
    if rc == 0:
        print(f"gist synced (ENGINE {ev}, patch {patch}, {n} files) - {url}")
    return rc


if __name__ == "__main__":
    raise SystemExit(sync())
