# arch: secret-gist mirror of the Share/ review package | section=tools | frozen=no
"""Mirror C:\\Riot Commander\\Share into the secret review gist.

The gist is the low-friction external handoff. It holds exactly four files:
  * Share.zip                              the full review package (deterministic)
  * daemon_slayer_wiki_stats_extract.py    inline, readable
  * daemon_slayer_wiki_ability_extract.py  inline, readable
  * README.md                              a generated tldr

This script regenerates all four into the gist clone, commits, and pushes - so
the gist stays current every time Share/ changes. It is wired to a git
post-commit hook on the RC repo (fires only when a commit touches Share/).

Share/ itself is a deterministic mirror regenerated by tools/ds_share_sync.py;
this is the next link in that chain: Share/ -> secret gist.

CLONE_DIR is a local clone of the gist - a SEPARATE git repo, kept OUT of the RC
tree. Its git remote holds the gist id; nothing here hardcodes it. Override the
clone path with RC_SHARE_GIST_DIR.

The zip is byte-deterministic (fixed entry timestamps + sorted order) so an
unchanged Share/ produces an unchanged zip -> no spurious gist commit.
"""
from __future__ import annotations

import os
import re
import subprocess
import sys
import zipfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
SHARE_DIR = REPO_ROOT / "Share"
CLONE_DIR = Path(
    os.environ.get("RC_SHARE_GIST_DIR", r"C:\Users\Administrator\.rc-share-gist")
)
WIKI_SCRIPTS = (
    "daemon_slayer_wiki_stats_extract.py",
    "daemon_slayer_wiki_ability_extract.py",
)
_EXCLUDE_DIR_NAMES = {"__pycache__"}
_EXCLUDE_SUFFIXES = (".pyc", ".pyo")
_ZIP_EPOCH = (1980, 1, 1, 0, 0, 0)  # fixed -> deterministic zip bytes

_README_TEMPLATE = """# Daemon Slayer - external review handoff

Daemon Slayer is an offline, deterministic League of Legends math engine. It
scores item builds for a champion at a given level and game mode against a
target's defensive profile - auto-attack DPS, ability DPS, burst, effective HP,
heal/shield throughput, and crowd-control pressure - and ranks builds across six
archetypes (carry, tank, bruiser, mage, assassin, enchanter). Pure Python, no
third-party runtime dependencies, served over a local HTTP endpoint.

This gist is the low-friction handoff:

- **Share.zip** - the full self-contained review package: the engine source and
  tests, the data tooling, the versioned reference-data snapshot, and five
  authored docs under `docs/`. Unzip and start at `docs/01_OVERVIEW.md`.
- The two wiki-extraction scripts below, inline for a quick read.

## The wiki extraction (the alignment starting point)

Both scripts pull from the League community wiki's Lua data via the MediaWiki
API - no HTML scraping.

- **daemon_slayer_wiki_stats_extract.py** - per-champion scalar sidecar
  (auto-attack cast time, missile speed, per-mode modifiers). PRIMARY fetch is
  ONE request: `action=raw` on `Module:ChampionData/data` (a ~380 KB Lua
  `return {...}` table), brace-scanned and keyed by each block's `apiname`
  (== the Riot / Data Dragon champion id). The raw table stores explicit stat
  scalars for only ~49 of 171 champions; a CommunityDragon character-bin
  backfill fills the rest (the wiki value wins where present; each scalar
  carries a `*_src` provenance tag).
- **daemon_slayer_wiki_ability_extract.py** - per-ability param sidecar
  (static-cooldown flag, recharge time, typed CC-class booleans, geometry).
  Built from the SAME `Module:ChampionData/data` raw module (it reuses the
  brace parse to resolve each ability's display name), then BATCHED via
  `action=query&prop=revisions` over `Template:Data <Champion>/<Ability>`
  titles - up to 50 titles per request (~22 requests for the whole roster, not
  ~1080 one-at-a-time).

## Access notes (verified live)

- Host is `https://wiki.leagueoflegends.com` (the Riot vanity alias for the
  wiki.gg backend). The bare `leagueoflegends.wiki.gg` host edge-blocks some
  egress (HTTP 401, host-wide); the alias is reachable.
- The User-Agent MUST be non-browser (a `Mozilla/5.0` UA trips a Cloudflare
  challenge -> 403). stdlib `urllib` only.
- CC duration in SECONDS is NOT a queryable wiki param - it lives only in the
  free-text leveling / description lines. These tools do not extract it.

## A note on the inline code comments

Both scripts (and the source inside Share.zip) carry internal development tags -
version anchors and incremental change markers. They are historical development
notes, not part of any public contract or external dependency.

---
ENGINE_VERSION __EV__ - data patch __PATCH__
"""


def read_manifest() -> tuple[str, str]:
    """(engine_version, patch) parsed from Share/MANIFEST.md; '?' if absent."""
    ev = patch = "?"
    mf = SHARE_DIR / "MANIFEST.md"
    if mf.exists():
        text = mf.read_text(encoding="utf-8")
        m = re.search(r"ENGINE_VERSION:\s*([0-9][0-9.]*)", text)
        if m:
            ev = m.group(1)
        m = re.search(r"data patch:\s*([0-9][0-9.]*)", text)
        if m:
            patch = m.group(1)
    return ev, patch


def render_readme(ev: str, patch: str) -> str:
    return _README_TEMPLATE.replace("__EV__", ev).replace("__PATCH__", patch)


def iter_share_files():
    """Yield (abs_path, arcname) for every Share/ file minus build artifacts."""
    for path in sorted(SHARE_DIR.rglob("*"), key=lambda p: p.as_posix()):
        if not path.is_file():
            continue
        rel = path.relative_to(SHARE_DIR)
        if any(part in _EXCLUDE_DIR_NAMES for part in rel.parts):
            continue
        if path.suffix in _EXCLUDE_SUFFIXES:
            continue
        yield path, "Share/" + rel.as_posix()


def build_zip(dest: Path) -> int:
    """Write a byte-deterministic Share.zip at dest. Returns the entry count."""
    count = 0
    tmp = dest.with_name(dest.name + ".tmp")
    with zipfile.ZipFile(tmp, "w", compression=zipfile.ZIP_DEFLATED) as zf:
        for path, arcname in iter_share_files():
            info = zipfile.ZipInfo(arcname, date_time=_ZIP_EPOCH)
            info.compress_type = zipfile.ZIP_DEFLATED
            info.external_attr = 0o644 << 16
            zf.writestr(info, path.read_bytes())
            count += 1
    os.replace(tmp, dest)
    return count


def _git(*args: str) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["git", "-C", str(CLONE_DIR), *args],
        check=True,
        capture_output=True,
        text=True,
    )


def _clear_clone() -> None:
    """Remove every tracked top-level entry except .git (gists are flat)."""
    for child in CLONE_DIR.iterdir():
        if child.name == ".git":
            continue
        if child.is_file():
            child.unlink()


def sync() -> int:
    if not (CLONE_DIR / ".git").is_dir():
        sys.stderr.write(
            f"gist clone missing at {CLONE_DIR}\n"
            "create the gist + clone it there first (see tools/gist_share_sync.py header)\n"
        )
        return 2

    ev, patch = read_manifest()
    _clear_clone()
    (CLONE_DIR / "README.md").write_text(render_readme(ev, patch), encoding="utf-8")
    for name in WIKI_SCRIPTS:
        src = SHARE_DIR / "src" / "tools" / name
        (CLONE_DIR / name).write_text(src.read_text(encoding="utf-8"), encoding="utf-8")
    n = build_zip(CLONE_DIR / "Share.zip")

    _git("add", "-A")
    status = _git("status", "--porcelain").stdout.strip()
    if not status:
        url = _git("remote", "get-url", "origin").stdout.strip()
        print(f"gist up to date (no change) - {url}")
        return 0

    msg = (
        f"sync Share -> gist (ENGINE {ev}, patch {patch}, {n} files)\n\n"
        "Co-Authored-By: Claude Opus 4.8 <noreply@anthropic.com>"
    )
    _git("commit", "-m", msg)
    _git("push", "origin", "HEAD")
    url = _git("remote", "get-url", "origin").stdout.strip()
    print(f"gist synced (ENGINE {ev}, patch {patch}, {n} files) - {url}")
    return 0


if __name__ == "__main__":
    raise SystemExit(sync())
